groups:
- name: hyperion.task.cpu.usage.rules
  rules:
  - alert: task.cpu.usage.50
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[1m])) BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) * 100 > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{ $labels.container_label_com_docker_swarm_node_id }}'' CPU usage is at {{ humanize $value}}%.'
      summary: CPU [50%] ALERT FOR TASK '{{ $labels.container_label_com_docker_swarm_task_name }}' ON '{{ $labels.container_label_com_docker_swarm_node_id }}'
  
  - alert: task.cpu.usage.80
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[1m])) BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) * 100 > 80
    for: 1m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{ $labels.container_label_com_docker_swarm_node_id }}'' CPU usage is at {{ humanize $value}}%.'
      summary: CPU [80%] ALERT FOR TASK '{{ $labels.container_label_com_docker_swarm_task_name }}' ON '{{ $labels.container_label_com_docker_swarm_node_id }}'