groups:
- name: hyperion.task.memory.usage.rules
  rules:
  - alert: task.memory.usage.512mb
    expr: sum(container_memory_rss{container_label_com_docker_swarm_task_name=~".+"}) BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) > 5e+8
    for: 1m
    labels:
      severity: warning
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{ $labels.container_label_com_docker_swarm_node_id }}'' memory usage is {{ humanize $value}}.'
      summary: MEMORY [512MB] ALERT FOR TASK '{{ $labels.container_label_com_docker_swarm_task_name }}' ON '{{ $labels.container_label_com_docker_swarm_node_id }}'
  
  - alert: task.memory.usage.1gb
    expr: sum(container_memory_rss{container_label_com_docker_swarm_task_name=~".+"}) BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) > 1e+09
    for: 1m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{ $labels.container_label_com_docker_swarm_node_id }}'' memory usage is {{ humanize $value}}.'
      summary: MEMORY [1GB] ALERT FOR TASK '{{ $labels.container_label_com_docker_swarm_task_name }}' ON '{{ $labels.container_label_com_docker_swarm_node_id }}'
