global:
  scrape_interval:     5m
  evaluation_interval: 5m

  external_labels:
    monitor: 'hyperion'

rule_files:
  - "node.cpu.usage.rules.yml"
  - "node.disk.fill.rules.yml"
  - "node.disk.usage.rules.yml"
  - "node.memory.usage.rules.yml"
  - "task.memory.usage.rules.yml"
  - "task.cpu.usage.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'metric-discovery'
    file_sd_configs:
      - files:
        - /etc/hyperion/discovery/providor.json
